[package]
author="Ivar Jönsson"
name = "mars"
version = "0.1.0"
edition = "2021"
[lib]
name = "matrs"
path = "src/mod.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debug_print = "1.0.0"
